### ISSUE TITLE
Menu Bar: Home Screen button cause crash.

### ISSUE THREAD

**Issue by innocentius** [BunkersAndBadasses/MetaDND#10]
Category: Bug
Level: High
Description: 
1. Open the app
2. in the home screen, go to menu bar, click "home screen".
3. there will be a new window opened, close it.
4. click on player button, the program will crash.

Exception in thread "main" org.eclipse.swt.SWTException: Widget is disposed
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.widgets.Widget.error(Unknown Source)
    at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
    at org.eclipse.swt.widgets.List.removeAll(Unknown Source)
    at guis.HomeWindow.loadCharacters(HomeWindow.java:530)
    at guis.HomeWindow$8.handleEvent(HomeWindow.java:445)
    at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
    at guis.HomeWindow.run(HomeWindow.java:124)
    at guis.HomeWindow.<init>(HomeWindow.java:115)
    at core.Main.main(Main.java:22)

**Comment by innocentius** [comment]
Check and fixed.
