### ISSUE TITLE
Loot Generation: Array Out Of Bound Crash

### ISSUE THREAD

**Issue by innocentius** [BunkersAndBadasses/MetaDND#21]
Category: Bug
Level: High
Description: The loot generate break after several tries, the error message is attached:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at guis.HomeWindow$14.handleEvent(HomeWindow.java:710)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
    at guis.HomeWindow.run(HomeWindow.java:148)
    at guis.HomeWindow.<init>(HomeWindow.java:138)
    at core.Main.main(Main.java:22)

**Comment by innocentius** [comment]
Fixed.
int weapon = rng.GetRandomInteger(0, weaponsNum) - 1;
to
int weapon = rng.GetRandomInteger(0, weaponsNum - 1);
